name: 'Smart Commits AI Demo'
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ai-commit-demo:
    runs-on: ubuntu-latest
    name: 'Generate AI Commit Messages'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate AI Commit Message
        id: smart-commits
        uses: ./  # Use local action for testing
        with:
          api_key: ${{ secrets.GROQ_API_KEY }}
          provider: 'groq'
          model: 'llama3-70b-8192'
          max_chars: '250'

      - name: Display Generated Message
        run: |
          echo "🤖 AI Generated Commit Message:"
          echo "${{ steps.smart-commits.outputs.commit_message }}"
          echo "Success: ${{ steps.smart-commits.outputs.success }}"

      - name: Use in Actual Commit (Example)
        if: steps.smart-commits.outputs.success == 'true'
        run: |
          echo "Would commit with message: ${{ steps.smart-commits.outputs.commit_message }}"
          # In real usage, you might do:
          # git commit -m "${{ steps.smart-commits.outputs.commit_message }}"
